### ISSUE TITLE
Docker proxy registry

### ISSUE THREAD

**Issue by g4s8** [artipie/docker-adapter#160]
Implement Docker proxy registry (or Docker mirror) with authentication and cache support. Default Docker mirror is described here: https://docs.docker.com/registry/recipes/mirror/

## Multi-remote

Docker proxy registry can be used to merge multiple remote registries into single one. In this case, proxy registry is trying to access remotes one by one in specified order until find applicable image.

*Example: user uses same Artipie docker proxy to access some private registry and Docker-hub, it specifies private registry first to pull images from it first. If proxy failed to pull the image, it tries to pull it from docker-hub.*

## Authentication

Proxy should be able to use authentication to access remote registry. The use case is when the user is giving access to different registries through proxy or hiding actual credentials on proxy side.

## Caching

Proxy should be able to cache blobs and metadata, the user can configure the TTL of the cache. Proxy needs to check HTTP cache control directives when pulling remote image, docker [PULL API V2](https://docs.docker.com/registry/spec/api/#pulling-a-layer) supports HTTP caching:

> This endpoint should support aggressive HTTP caching for image layers. Support for Etags, modification dates and other cache control headers should be included. To allow for incremental downloads, Range requests should be supported, as well.

Docker proxy should use cache directives as well to avoid redundant downloads.

### Configuration

The suggested configuration for proxy registry for Artipie is:
```yaml
repository:
  type: docker-proxy
  remotes:
    - url: https://registry-1.docker.io # required
      username: admin # optional
      password: qwerty # optional
      cache: # optional
        ttl: 5d # optional
        maxSize: 10G # optional
    - url: https://registry.hub.docker.com
```
